#!/bin/bash

donar () {

			 bot_retorno="$LINE\n"
			 bot_retorno+="El proyecto BotGen requiere\nde fondos para poder continuar\n"
			 bot_retorno+="Usted puede realizar una donacion\n"
			 bot_retorno+="Paypal\n"
			 bot_retorno+="PAGO BTC - CRIPTOMONEDA\n"
			 bot_retorno+="O Bien Contactando a WHATSAPP\n DIRECTAMENTE\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+="Desde ya muchas gracias\n"
			 bot_retorno+="$LINE\n"
			 msj_donar
}

donar_OnOff () {
if [[ ! -e "/etc/donar_active.txt" ]]; then
	echo "on" > /etc/donar_active.txt
	local bot_retorno="$LINE\n"
          bot_retorno+="MENSAJE DONATIVO : <u>ENCENDIDO</u> ✅\n"
	  bot_retorno+="$LINE\n"
	msj_fun
else
	rm -rf /etc/donar_active.txt
	local bot_retorno="$LINE\n"
          bot_retorno+="MENSAJE DONATIVO: <u>APAGADO</u> ❌\n"
	  bot_retorno+="$LINE\n"
	msj_fun
fi
}
