#!/bin/bash

idirect="/etc/idir" && [[ ! -d $idirect ]] && mkdir $idirect

myid_src () {
bot_retorno="====================\n"
          bot_retorno+="SU ID: ${chatuser}\n"
          bot_retorno+="====================\n"
msj_fun
}

deleteID_reply () {
delid=$(sed -n ${message_text[$id]}p ${CID})
sed -i "${message_text[$id]}d" ${CID}
bot_retorno="$LINE\n"
          bot_retorno+="ID eliminado con exito!\n"
          bot_retorno+="ID: ${delid}\n"
          bot_retorno+="$LINE\n"
msj_fun
upfile_src
}

addID_reply () {
      [[ $(cat ${CID}|grep "${message_text[$id]}" ) = "" ]] && {
        #echo "/${message_text[$id]} | $(date '+%d-%m-%Y' -d " +$dias days")" >> $idirect/idtegm
        #cat $idirect/idtegm | awk '{print $1}' >> ${CID}
        echo "/${message_text[$id]}" >> ${CID}
          bot_retorno="  🎊 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  $message_from_first_name  𝚊𝚕  𝙱𝚘𝚝𝙶𝚎𝚗  𝙲𝚑𝚞𝚖𝚘𝙶𝙷-𝙰𝙳𝙼  🎊\n"
          bot_retorno+="✅ *ID agregado * ✅\n"
          bot_retorno+="$LINE\n"
          bot_retorno+="$(< ${CID})\n"
          bot_retorno+="$LINE\n"
          bot_retorno+="New ID: ${message_text[$id]}\n"
          bot_retorno+="$LINE"

          bot_retor="  🎊 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  Nuevamente 𝚊𝚕  𝙱𝚘𝚝𝙶𝚎𝚗  𝙲𝚑𝚞𝚖𝚘𝙶𝙷-𝙰𝙳𝙼  🎊\n"
          bot_retor+="𝙃𝙤𝙡𝙖 『 $message_from_first_name $message_from_last_name 』\n"
          bot_retor+="El Administrador $(cat < /etc/ADM-db/resell) te autorizo\n"
          bot_retor+="Para GENERAR Key's usar el comando /keygen\n"
          bot_retor+="Para MENU Digita el comando /menu\n"
          bot_retor+="Para actualizar el menu de comandos\n"
          bot_retor+="$LINE"
          bot_retor+="Recuerda adquirir creditos, o Realizar tu donativo Voluntario  \n Paypal : chumogh@gmail.com\n"
          bot_retor+="Si tienes inconvenientes con el Bot \n Contactame : https://wa.me/593987072611\n"
          bot_retor+="$LINE\n"
      msj_fun
      msj_add ${message_text[$id]}
      upfile_src
    } || {
          bot_retorno="====ERROR====\n"
          bot_retorno+="Este ID ya existe\n"
          bot_retorno+="$LINE\n"
      msj_fun
    }
}










