#!/bin/bash
link_src () {
	bot_retorno="$LINE\n"
	bot_retorno+=" 💥 Instalador Oficial 💥 \n 🧬 Soporte : Ubuntu 14.04 - 16.04 - 18.04 - 20.04 \n"
	bot_retorno+="Verificada tus Keys, https://t.me/ChumoGH_bot Reseller : @ChumoGH \n"
	bot_retorno+="$LINE\n"
	bot_retorno+="wget -q https://www.dropbox.com/s/0qj3edi5dibcrqd/instala.sh; chmod 777 instala.sh; ./instala.sh\n"
	bot_retorno+="$LINE\n"
msj_fun
}
