#!/bin/bash
upact="apt update -y && apt upgrade -y; \n"
link_src () {
	bot_retorno="$LINE\n"
	bot_retorno+=" 💥 Instalador Oficial 💥\n 🧬 Soporte : Ubuntu 14.04 - 16.04 - 20.04 \n"
	bot_retorno+="Verificada tus Keys, https://t.me/ChumoGH_bot Reseller : @ChumoGH \n"
	bot_retorno+="$LINE\n"
	bot_retorno+="$upact"
	bot_retorno+="wget -q https://www.dropbox.com/s/i87udxpj1lj17sa/instala.sh; chmod +x instala.sh;./instala.sh \n"
	bot_retorno+="$LINE\n"
msj_fun
}
